---
title: "test"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Can test code here

```{r}
source('load_package.R')
```

```{r}
# Produce data
set.seed(1234)
n = 1000
p = 7
X_nointercept = matrix(rnorm(n * p), nrow=n)
X = cbind(1, X_nointercept)
beta = c(1:(p-1), 0, 0)
y = X %*% beta + rnorm(n, sd=0.4)

df = data.frame(X_nointercept)
df$y_response = y

fit = ols_fit(X,y)
lm_fit = lm(y_response ~ X1 + X2 + X3 + X4 + X5, data=df)
summary(lm_fit)
ols_summary(fit)
```

```{r}
# Testing individual coefficients
coef_inference(fit, b=c(1,2,3,4,5,6,0,0) - 0.03, bonf=T)
```

```{r}
# Testing multiple coefficients
multicoef_inference(fit, testeq0=c(7,8))
multicoef_inference(fit, testeq0=c(7))
multicoef_inference(fit, testeq0=c(1,7,8))
```

```{r}
# Testing row conditions
R1 = matrix(c(2,-1,0,0,0,0,0,0), nrow=1, byrow=T)
R2 = matrix(c(2,-1,0,0,0,0,0,0, 
              4,0,0,-1,0,0,0,0), nrow=2, byrow=T)
R3 = matrix(c(0,2,-1,0,0,0,0,0,
              0,0,0,2,0,-1,0,0), nrow=2, byrow=T)
r3 = c(1,2)
R1
R2
R3

test_row_constraints(fit, R1)
test_row_constraints(fit, R2)
test_row_constraints(fit, R3, r=r3)
test_row_constraints(fit, R3, r=r3+0.05)
```

